version: '3.9'

services:
  app-1:
    image: node-app:1.0
    build: 
      context: ./app
      dockerfile: docker/Dockerfile
    ports:
      - 8080:8080
  
  app-2:
    image: node-app:1.0
    ports:
      - 8081:8080
  
  http-alb:
    image: nginx:1.27.0-perl
    volumes:
      -  ./config/:/etc/nginx/conf.d/
    ports:
      - 90:80